config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'places#index' 

  resources :places do 
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #ustvarjeni routi
  get '/index' => 'places#index'
  get '/show' => 'places#show'
  get '/edit' => 'places#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
has_many :comments, dependent: :destroy
belongs_to :user
mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
has_many :place, dependent: :destroy
has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
         user = User.create(email: data['email'],
            password: Devise.friendly_token[0,20]
         )
     end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
    	@comment = current_user.comments.build
  	end

	def create
		@comment = current_user.comments.build(comment_params)
		@place = Place.find(params[:place_id])	
		@comment.place_id = @place.id
		@comment.save
		redirect_to place_path(@place)
	end

	def destroy
		@place = Place.find(params[:place_id])
		@comment = @place.comments.find(params[:id])
		@comment.destroy
		redirect_to place_path(@place)
	end


	private
	def comment_params
      params.require(:comment).permit(:body, :user_id, :place_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

#################### Administratorji ##########

#if current_user.admin == false
    #    current_user.admin = true
    #    current_user.save
    #end
#################### Administratorji ##########    

    # GET /place
  # GET /place.json
  def index
    @place = Place.all
  end

  # GET /place/1
  # GET /place/1.json
  def show
  end

  # GET /place/new
  def new
    @place = Place.new
  end

  # GET /place/1/edit
  def edit
  end

  # POST /place
  # POST /place.json
  def create
    #@place = Place.new(place_params)
    
    #zgoraj je orginal
    #da ustvarimo povezavo, bo sedaj user ustvaril destinacijo in se bo zato shranil njegov tuji ključ
    #v spremenljivki current_user je objekt trenutno prijavljenega uporabnika
  if current_user.admin == true
    @place = current_user.place.build(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
    end
  if current_user.admin == false
     respond_to do |format|
        format.html { redirect_to places_path, notice: 'You have to be an admin to perform this action.' }
      end
  end
  end

  # PATCH/PUT /place/1
  # PATCH/PUT /place/1.json
  def update
    #opcijsko, če že imate vnešene kakšne destinacije, preden ste uredili prijavo in povezavo z uporabnikom
    #potem bi ob vsakem urejanju se pod uporabnika vpisal uporabnik, ki trenutno ureja destinacijo
  if current_user.admin == true
    @place.user = current_user
    
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  if current_user.admin == false
    format.html { redirect_to @place, notice: 'You have to be admin to perform this action.' }
  end
  end
  end

  # DELETE /place/1
  # DELETE /place/1.json
  def destroy
  if current_user.admin == true
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_path, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:ime, :opis, :lokacija, :kraj, :image)
    end
end

app/controllers/users/omniauth_callbacks.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/_comment.html.erb
<div class="card" >
  <div class="card-body">
    <h5 class="card-text"><%= comment.user.email %>
    <% if comment.user.admin == true %>
    (ADMIN)
    <% end %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= time_ago_in_words(comment.created_at) %></h6>
    <h4 class="card-text"><%= comment.body %></h4>
    <% if user_signed_in? %>
	<% if comment.user_id == current_user.id %>
	<div class="btn btn-danger"><%= link_to 'Delete',[comment.place,comment], method: :delete, data: {confirm: 'Are you sure?'} %></div>
	<% end %>
	<% end %>
	</a>
  </div>
</div>

app/views/comments/_form.html.erb
<style> 
textarea {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
}
</style>

<%= form_for([@place, @place.comments.build]) do |f| %>
<p>
	<%= f.text_area :body %><br>
	 <button type="submit" class="btn btn-primary">Dodaj komentar</button>
	<% end %>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<style>
.btn a {
  color:white;
  text-decoration: none;
}
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/index">Nepremičnine</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/index">Domov <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>
      <% if current_user.admin == true %>
      <div class="btn btn-success">
      	<%= link_to 'Dodaj nepremičnino', new_place_path %>
      </div>
      <% end %>
      <% end %>
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>-->
    <div class="btn btn-primary">
      <% if user_signed_in? %>
        <a id="uporabnik"><%= link_to('Odjava', destroy_user_session_path, method: :delete) %></a>
      <% else %>
      <%= link_to "Prijava", new_user_session_path %>
      </div>
      <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <title>Nepremicnine App</title>
    <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	  <link rel="stylesheet" href="/resources/demos/style.css">

	  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  	  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
    $( "#resizable" ).resizable({
      animate: false,
      maxHeight: 600,
      maxWidth: 900,
      minHeight: 200,
      minWidth: 300,
      aspectRatio: 300 / 200,
      ghost: true
    });
  } );
  </script>
  </head>
<body>
 <%= render 'layouts/navbar' %>
 <p id="notice"><%= notice %></p>	
       <p class="alert"><%= alert %></p>
    <%= yield %>
</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place, :html => {:multipart => true} do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :ime %><br>
    <%= f.text_field :ime, id: :place_ime, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :opis %><br>
    <%= f.text_area :opis, id: :place_opis, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :lokacija %><br>
    <%= f.text_field :lokacija, id: :place_lokacija, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :kraj %><br>
    <%= f.text_field :kraj, id: :place_kraj, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Upload</span>
  </div>
  <div class="custom-file">
    <%= f.file_field :image, class: "custom-file-input" %> 
    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
  </div>
</div>

  <div class="actions">
    <button type="submit" class="btn btn-primary">Dodaj</button><br><br>
  </div>
<% end %>

app/views/places/edit.html.erb
<style>
.body {
  width: 100%;
  margin: 0 auto;
}
</style>
<div class="body">
<div class="row">
<div class="col-3"></div>
<div class="col-6">
<h1>Uredi nepremičnino</h1>

<%= render 'form', place: @place %>

<div class="btn btn-secondary"><%= link_to 'Show', @place %></div> |
<div class="btn btn-secondary"><%= link_to 'Back', places_path %></div>
</div>
<div class="col-3"></div>
</div>
</div>

app/views/places/index.html.erb
<style>

.btn a {
  color:white;
  text-decoration: none;
}

.body {
  margin: auto;
}

.slika {
  height: 200px;
  width: 300px;
}
</style>
<div class="body">
<div class="row">
<div class="col-3"></div>
<div class="col-6">

<h1>Nepremičnine</h1>

<% @place.each do |place| %>
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title"><%= place.ime %></h5>
    <%= image_tag place.image_url.to_s, class: "slika" %><br>
    <p class="card-text"><%= place.opis %></p>
    <p class="card-text">Lokacija: <%= place.lokacija %></p>
    <p class="card-text">Kraj: <%= place.kraj %></p>
    <div class="btn btn-info"><%= link_to 'Pokaži', place %></div>
    <% if user_signed_in? %>
    <% if current_user.admin == true %>
    <div class="btn btn-primary"><%= link_to 'Uredi', edit_place_path(place) %></div>
    <div class="btn btn-danger"><%= link_to 'Izbriši', place, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% end %>
    <% end %>
  </div>
</div>
<% end %>
<br>
</div>
<div class="col-3"></div>
</div>
</div>

app/views/places/new.html.erb
<style>
.body {
  width: 100%;
  margin: 0 auto;
}
</style>
<div class="body">
<div class="row">
<div class="col-3"></div>
<div class="col-6">
<h1>Dodaj nepremičnino</h1>

<%= render 'form', place: @place %>

<div class="btn btn-secondary"><%= link_to 'Back', places_path %></div>
</div>
<div class="col-3"></div>
</div>
</div>

app/views/places/show.html.erb
<style>
hr {
  margin-top:3em;
  margin-bottom: 3em;
}

h3 {
  font-weight: normal;
}

h4 a {
  color: black;
}

h4 a:hover {
  color: black;
}

  #resizable { width: 300px; height: 200px; padding: 1em; }
  #resizable h3 { text-align: center; margin: 0; }

.slika {
  width:100%;
  height: 100%;
}
</style>

<div class="row">
<div class="col-3"></div>
<div class="col-6">
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @place.ime %></h1>
</p>

<div id="resizable" class="ui-widget-content">
<%= image_tag @place.image_url.to_s, class: "slika" %>
</div>

<p>
  <h3><%= @place.opis %></h2>
</p>

<p>
  <strong>Lokacija:</strong>
  <%= @place.lokacija %>
</p>

<p>
  <strong>Kraj:</strong>
  <%= @place.kraj %>
</p>
<hr>
<div class="komentarji">
<h4>Komentarji:</h4><br>
<section id="comments-section">
<div class="komentar">
	<%= render @place.comments %>
</div>
<% if user_signed_in? %>
<div class="dodaj_kom">
	<h3>Dodaj komentar:</h3>
	<%= render "comments/form" %>
</div>
</section>
<% if current_user.admin == true && %>
<div class="btn btn-secondary"><%= link_to 'Edit', edit_place_path(@place) %></div> |
<% end %>
<% end %>
<div class="btn btn-secondary"><%= link_to 'Back', places_path %></div>
<div class="col-3"></div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>